apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentry-pod
  namespace: secure-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentry-pod
  template:
    metadata:
      labels:
        app: sentry-pod
    spec:
      containers:
      - name: sentry-pod
        image: sentry-pod:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"